linters:
  disable:
    - exhaustruct
    - nlreturn
    - varnamelen
    - wrapcheck
    - wsl
  enable-all: true

linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - fyne.io/fyne
          - github.com/tfpf/riven
