linters:
  disable:
    - exhaustruct
    - gci
    - gofumpt
    - goimports
    - nlreturn
    - varnamelen
    - wrapcheck
    - wsl
  enable-all: true

linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - fyne.io/fyne
          - github.com/tfpf/riven
  gosec:
    excludes:
      - G306
  mnd:
    ignored-numbers:
      - '0644'
