name: ci
on: [push, workflow_dispatch]

jobs:
  build_lint:
    strategy:
      matrix:
        os: ['macos-13', 'macos-14', 'windows-2022']
    name: build and lint on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: make build
        name: Build (download dependencies to prevent timeout when linting)
      - uses: golangci/golangci-lint-action@v6
        with:
          skip-cache: true
          version: v1.60
        name: Lint
