name: ci
on: [push, workflow_dispatch]

jobs:
  lint:
    strategy:
      matrix:
        os: ['macos-13', 'macos-14', 'windows-2022']
    name: build and lint on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
      - run: make build
        name: Download dependencies for linter to examine
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
