name: lint
on: [push, workflow_dispatch]

jobs:
  Go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
      - run: sudo apt-get install libx11-dev libxcursor-dev
      - run: make build
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
