name: lint
on: [push, workflow_dispatch]

jobs:
  Go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
