name: lint
on: [push, workflow_dispatch]

jobs:
  Go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - run: [ -z $(gofmt -l .) ]
